name: Simple Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Show Initial Space
        run: |
          echo "Before cleanup:"
          df -h /

      - name: Clean APT
        run: |
          sudo apt-get clean
          sudo apt-get autoclean
          sudo apt-get autoremove -y

      - name: Clean Docker
        run: |
          docker system prune -af || true

      - name: Clean Temp Files
        run: |
          sudo rm -rf /tmp/* || true
          sudo rm -rf /var/tmp/* || true

      - name: Clean Cache
        run: |
          rm -rf ~/.cache/* || true
          sudo rm -rf /var/cache/apt/archives/* || true

      - name: Clean Logs
        run: |
          sudo journalctl --vacuum-time=1d || true
          sudo rm -rf /var/log/*.log* || true

      - name: Clean Large Dirs
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache || true

      - name: Drop Caches
        run: |
          sync
          echo 3 | sudo tee /proc/sys/vm/drop_caches

      - name: Show Final Space
        run: |
          echo "After cleanup:"
          df -h /
